# Generated by Django 2.1.7 on 2019-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Man'), ('female', 'Woman')], max_length=6, null=True, verbose_name='Gender')),
                ('first_name', models.CharField(blank=True, max_length=99, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=99, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=99, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('ip', models.CharField(blank=True, max_length=99, null=True, verbose_name='IP Address')),
                ('cid', models.CharField(blank=True, max_length=199, null=True, verbose_name='Voluum Click ID')),
                ('stripe_id', models.CharField(blank=True, max_length=199, null=True, verbose_name='Stripe Purchase ID')),
            ],
        ),
    ]
