# Generated by Django 2.1.7 on 2019-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('paused', 'Paused')], default='draft', max_length=9, verbose_name='Status')),
                ('title', models.CharField(default='Default Title', max_length=99, verbose_name='Testimonial Title')),
                ('testimonial', models.CharField(default='Lorum ipsum dolor sit amet...', max_length=1999, verbose_name='Testimonial')),
                ('name', models.CharField(default='Baba Vanga', max_length=99, verbose_name='Name')),
                ('location', models.CharField(default='Virginia', max_length=99, verbose_name='Location/State')),
                ('picture', models.CharField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-744x744.jpg', max_length=999, verbose_name='Profile Pic (link)')),
            ],
        ),
    ]
